/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QuoteParams {
  /**
   * sqrtPriceX48 (Q32.48, uint80) as decimal or hex string.
   * Single canonical price — operator-set, swaps do not move it.
   */
  sqrtPriceX48: string
  /** fee charged on Y → X swaps in Q24 (uint24). */
  feeAskX24: number
  /** fee charged on X → Y swaps in Q24 (uint24). */
  feeBidX24: number
  /** reserve X as decimal or hex string */
  reserveX: string
  /** reserve Y as decimal or hex string */
  reserveY: string
  /** concentration multiplier in Q20.12 (uint32). Effective K = concentration_k / 2^12. */
  concentrationK: number
  /** input amount as decimal or hex string */
  amountIn: string
}
export interface QuoteResult {
  /** output amount as decimal string */
  amountOut: string
  /** new Q32.48 sqrt price as decimal string */
  sqrtPriceNext: string
  /** fee amount as decimal string */
  fee: string
}
export declare function quoteXToY(params: QuoteParams): QuoteResult
export declare function quoteYToX(params: QuoteParams): QuoteResult
/**
 * **Deprecated** — Q48 is the canonical wire format after the Q48 migration.
 * Lift a Q32.48 sqrt-price (uint80) into a Q64.96 sqrt-price (uint160) by
 * shifting left 48 bits. Lossless. Pass decimal or 0x-hex string; result is decimal.
 *
 * Kept for interoperating with legacy serialised Q96 state.
 */
export declare function sqrtPriceX48ToX96(pX48: string): string
/**
 * **Deprecated** — Q48 is the canonical wire format after the Q48 migration.
 * Lower a Q64.96 sqrt-price (uint160) into a Q32.48 sqrt-price (uint80)
 * by right-shifting 48 bits. Truncates the bottom 48 bits of precision.
 *
 * Kept for migrating legacy Q96 serialised state.
 */
export declare function sqrtPriceX96ToX48(pX96: string): string
/**
 * Lift a plain effective `K` (e.g. `100`) into the Q20.12 representation
 * expected by `QuoteParams.concentrationK`. `plainToQ12ConcentrationK(100)
 * === 409_600`. Saturates at `0xFFFFFFFF` if the shift would overflow.
 */
export declare function plainToQ12ConcentrationK(k: number): number
/**
 * Lower a Q20.12 `concentration_k` back to its effective integer `K`
 * (truncated). `q12ToPlainConcentrationK(409_600) === 100`.
 */
export declare function q12ToPlainConcentrationK(kQ12: number): number
/**
 * Convert a plain decimal price into a Q32.48 sqrt-price (uint80) as a
 * decimal string. Throws on NaN/Infinity/negative price. Saturates at
 * `2^80 - 1` on overflow.
 */
export declare function priceToSqrtPriceX48(price: number): string
/**
 * Convert a Q32.48 sqrt-price (uint80) back to a plain decimal price.
 * Pass decimal or 0x-hex string. Lossy beyond JS `number`'s 53-bit significand.
 */
export declare function sqrtPriceX48ToPrice(pX48: string): number
/**
 * **Deprecated** — use [`priceToSqrtPriceX48`] in new code.
 * Convert a plain decimal price (e.g. `2500.0`) into a Q64.96 sqrt-price
 * (uint160). Lossy beyond JS `number`'s 53-bit significand; result is a
 * decimal string. Throws on NaN/Infinity/negative price.
 */
export declare function priceToSqrtPriceX96(price: number): string
/**
 * **Deprecated** — use [`sqrtPriceX48ToPrice`] in new code.
 * Convert a Q64.96 sqrt-price back to a plain decimal price (`(p/2^96)^2`).
 * Pass decimal or 0x-hex string; result is a JS `number`, lossy beyond
 * 53-bit significand.
 */
export declare function sqrtPriceX96ToPrice(pX96: string): number
