/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'lunarbase-pmm-math.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.android-arm64.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'lunarbase-pmm-math.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.android-arm-eabi.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'lunarbase-pmm-math.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'lunarbase-pmm-math.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'lunarbase-pmm-math.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'lunarbase-pmm-math.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./lunarbase-pmm-math.darwin-universal.node')
      } else {
        nativeBinding = require('@lunarbase-lab/pmm-math-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'lunarbase-pmm-math.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.darwin-x64.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'lunarbase-pmm-math.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.darwin-arm64.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'lunarbase-pmm-math.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./lunarbase-pmm-math.freebsd-x64.node')
      } else {
        nativeBinding = require('@lunarbase-lab/pmm-math-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-x64-musl.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'lunarbase-pmm-math.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./lunarbase-pmm-math.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@lunarbase-lab/pmm-math-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'lunarbase-pmm-math.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./lunarbase-pmm-math.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@lunarbase-lab/pmm-math-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { OrderBookStatus, OrderBookSafety, SwapSimulationStatus, quoteXToY, quoteYToX, simulateXToY, simulateYToX, buildOrderBook, buildValidatedOrderBook, buildPreciseOrderBook, validateFeeAccountingCapacity, ladderAmountOut, geometricSizes, priceToSqrtPriceX96, price_to_sqrt_price_x96, sqrtPriceX96ToPrice, sqrt_price_x96_to_price } = nativeBinding

module.exports.OrderBookStatus = OrderBookStatus
module.exports.OrderBookSafety = OrderBookSafety
module.exports.SwapSimulationStatus = SwapSimulationStatus
module.exports.quoteXToY = quoteXToY
module.exports.quoteYToX = quoteYToX
module.exports.simulateXToY = simulateXToY
module.exports.simulateYToX = simulateYToX
module.exports.buildOrderBook = buildOrderBook
module.exports.buildValidatedOrderBook = buildValidatedOrderBook
module.exports.buildPreciseOrderBook = buildPreciseOrderBook
module.exports.validateFeeAccountingCapacity = validateFeeAccountingCapacity
module.exports.ladderAmountOut = ladderAmountOut
module.exports.geometricSizes = geometricSizes
module.exports.priceToSqrtPriceX96 = priceToSqrtPriceX96
module.exports.price_to_sqrt_price_x96 = price_to_sqrt_price_x96
module.exports.sqrtPriceX96ToPrice = sqrtPriceX96ToPrice
module.exports.sqrt_price_x96_to_price = sqrt_price_x96_to_price
