/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QuoteParams {
  /** sqrtPriceX48 as decimal or hex string */
  sqrtPriceX48: string
  /** anchor sqrtPriceX48 as decimal or hex string. Defaults to sqrtPriceX48 when omitted by callers compiled against older API. */
  anchorSqrtPriceX48?: string
  /** fee in Q48 as decimal or hex string */
  feeQ48: string
  /** reserve X as decimal or hex string */
  reserveX: string
  /** reserve Y as decimal or hex string */
  reserveY: string
  /** concentration multiplier k */
  concentrationK: number
  /** input amount as decimal or hex string */
  amountIn: string
}
export interface QuoteResult {
  /** output amount as decimal string */
  amountOut: string
  /** new sqrt price as decimal string */
  sqrtPriceNext: string
  /** fee amount as decimal string */
  fee: string
}
export declare function quoteXToY(params: QuoteParams): QuoteResult
export declare function quoteYToX(params: QuoteParams): QuoteResult
