// ESM wrapper for the napi-rs native module.
// index.js is CJS (auto-generated by napi-rs), so we re-export via createRequire.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const binding = require("./index.cjs");

export const quoteXToY = binding.quoteXToY;
export const quoteYToX = binding.quoteYToX;
