// ESM wrapper for the napi-rs native module.
// index.js is CJS (auto-generated by napi-rs), so we re-export via createRequire.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const binding = require("./index.cjs");

export const SwapSimulationStatus = binding.SwapSimulationStatus;
export const OrderBookStatus = binding.OrderBookStatus;
export const buildOrderBook = binding.buildOrderBook;
export const buildValidatedOrderBook = binding.buildValidatedOrderBook;
export const buildPreciseOrderBook = binding.buildPreciseOrderBook;
export const validateFeeAccountingCapacity = binding.validateFeeAccountingCapacity;
export const ladderAmountOut = binding.ladderAmountOut;
export const OrderBookSafety = binding.OrderBookSafety;
export const geometricSizes = binding.geometricSizes;
export const quoteXToY = binding.quoteXToY;
export const quoteYToX = binding.quoteYToX;
export const simulateXToY = binding.simulateXToY;
export const simulateYToX = binding.simulateYToX;
export const priceToSqrtPriceX96 = binding.priceToSqrtPriceX96;
export const sqrtPriceX96ToPrice = binding.sqrtPriceX96ToPrice;
export const price_to_sqrt_price_x96 = binding.price_to_sqrt_price_x96;
export const sqrt_price_x96_to_price = binding.sqrt_price_x96_to_price;
