// ESM wrapper for the napi-rs native module.
// index.js is CJS (auto-generated by napi-rs), so we re-export via createRequire.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const binding = require("./index.cjs");

export const quoteXToY = binding.quoteXToY;
export const quoteYToX = binding.quoteYToX;
export const sqrtPriceX48ToX96 = binding.sqrtPriceX48ToX96;
export const sqrtPriceX96ToX48 = binding.sqrtPriceX96ToX48;
export const plainToQ12ConcentrationK = binding.plainToQ12ConcentrationK;
export const q12ToPlainConcentrationK = binding.q12ToPlainConcentrationK;
export const priceToSqrtPriceX96 = binding.priceToSqrtPriceX96;
export const sqrtPriceX96ToPrice = binding.sqrtPriceX96ToPrice;
export const priceToSqrtPriceX48 = binding.priceToSqrtPriceX48;
export const sqrtPriceX48ToPrice = binding.sqrtPriceX48ToPrice;
