//! Fuzz cross-validation: reads vectors generated by Solidity
//! `CurvePMMFuzzVectors.t.sol` and verifies every single one produces
//! identical output in Rust.
#![allow(clippy::module_name_repetitions, clippy::str_to_string)]

#[cfg(test)]
mod fuzz {
    use crate::curve_pmm::*;
    use crate::uint256::U256;

    struct FuzzVector {
        dir: String,
        sqrt_price_x48: u128,
        fee_x24: u32,
        res_x: u128,
        res_y: u128,
        k_q12: u32,
        amount_in: u128,
        amount_out: u128,
        p_next: u128,
        fee_amt: u128,
    }

    fn parse_u128(s: &str) -> u128 {
        s.trim_matches('"').parse::<u128>().unwrap()
    }

    fn extract_field<'a>(json: &'a str, key: &str) -> &'a str {
        let pattern = format!("\"{}\":", key);
        let start = json
            .find(&pattern)
            .unwrap_or_else(|| panic!("key '{}' not found in {}", key, json));
        let rest = &json[start + pattern.len()..];
        let rest = rest.trim_start();
        if let Some(inner) = rest.strip_prefix('"') {
            let end = inner.find('"').unwrap();
            &inner[..end]
        } else {
            let end = rest.find([',', '}'].as_ref()).unwrap();
            rest[..end].trim()
        }
    }

    fn parse_vector(line: &str) -> FuzzVector {
        let dir = extract_field(line, "dir").to_string();
        let sqrt_price_x48 = parse_u128(extract_field(line, "pX48"));
        let fee_x24 = parse_u128(extract_field(line, "fee")) as u32;
        let res_x = parse_u128(extract_field(line, "resX"));
        let res_y = parse_u128(extract_field(line, "resY"));
        let k_q12 = parse_u128(extract_field(line, "k")) as u32;
        let p_next = parse_u128(extract_field(line, "pNext"));
        let fee_amt = parse_u128(extract_field(line, "feeAmt"));

        let (amount_in, amount_out) = if dir == "xToY" {
            (
                parse_u128(extract_field(line, "dx")),
                parse_u128(extract_field(line, "dy")),
            )
        } else {
            (
                parse_u128(extract_field(line, "dy")),
                parse_u128(extract_field(line, "dx")),
            )
        };

        FuzzVector {
            dir,
            sqrt_price_x48,
            fee_x24,
            res_x,
            res_y,
            k_q12,
            amount_in,
            amount_out,
            p_next,
            fee_amt,
        }
    }

    #[test]
    fn test_all_fuzz_vectors() {
        let data = include_str!("../fuzz_vectors.jsonl");
        let mut total = 0u32;
        let mut x_to_y_count = 0u32;
        let mut y_to_x_count = 0u32;
        let mut failures = Vec::new();

        for (i, line) in data.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }

            let v = parse_vector(line);
            total += 1;

            let (fee_ask_x24, fee_bid_x24) = if v.dir == "xToY" {
                (0u32, v.fee_x24)
            } else {
                (v.fee_x24, 0u32)
            };
            let params = PoolParams {
                sqrt_price_x48: v.sqrt_price_x48,
                fee_ask_x24,
                fee_bid_x24,
                reserve_x: v.res_x,
                reserve_y: v.res_y,
                concentration_k: v.k_q12,
            };

            if v.dir == "xToY" {
                x_to_y_count += 1;
                let result = quote_x_to_y(&params, U256::from(v.amount_in));

                if result.amount_out != U256::from(v.amount_out)
                    || result.sqrt_price_next != v.p_next
                    || result.fee != U256::from(v.fee_amt)
                {
                    failures.push(format!(
                        "Line {}: xToY MISMATCH\n  dy: got {} expected {}\n  pNext: got {} expected {}\n  fee: got {} expected {}",
                        i + 1, result.amount_out, v.amount_out,
                        result.sqrt_price_next, v.p_next,
                        result.fee, v.fee_amt,
                    ));
                }
            } else {
                y_to_x_count += 1;
                let result = quote_y_to_x(&params, U256::from(v.amount_in));

                if result.amount_out != U256::from(v.amount_out)
                    || result.sqrt_price_next != v.p_next
                    || result.fee != U256::from(v.fee_amt)
                {
                    failures.push(format!(
                        "Line {}: yToX MISMATCH\n  dx: got {} expected {}\n  pNext: got {} expected {}\n  fee: got {} expected {}",
                        i + 1, result.amount_out, v.amount_out,
                        result.sqrt_price_next, v.p_next,
                        result.fee, v.fee_amt,
                    ));
                }
            }
        }

        eprintln!("Fuzz vectors: {total} total ({x_to_y_count} xToY, {y_to_x_count} yToX)");

        if !failures.is_empty() {
            eprintln!("\n{} FAILURES out of {}:", failures.len(), total);
            for (i, f) in failures.iter().enumerate().take(20) {
                eprintln!("\n[{}] {}", i + 1, f);
            }
            if failures.len() > 20 {
                eprintln!("\n... and {} more", failures.len() - 20);
            }
            panic!("{} out of {} vectors failed", failures.len(), total);
        }

        eprintln!("ALL {total} vectors passed!");
    }
}
